version: 1.0.{build}
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - jacques.bouthillier@ericsson.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
on_success:
- cmd: change
on_failure:
- cmd: always
